services:
  python-runner:
    build:
      context: ./py-runner  # Path to Python runner Dockerfile
    container_name: python-runner
    networks:
      - code-runner-network

  c-runner:
    build:
      context: ./c-runner  # Path to C runner Dockerfile
    container_name: c-runner
    networks:
      - code-runner-network

  proxy-server:
    build:
      context: ./proxy-server  # Path to Proxy server Dockerfile
    container_name: proxy-server
    ports:
      - "8080:8080"  # Proxy server port
    networks:
      - code-runner-network
    depends_on:
      - python-runner
      - c-runner

networks:
  code-runner-network:
    driver: bridge